- doc/developper-documentation/cookbooks/customize_error_pages.md
- doc/js/backbee.js
- mkdocs.yml
REFS backbee/backbee-standard#170
> Added Customize error pages cookbook

- doc/index.md
REFS https://github.com/backbee/backbee-standard/issues/170
Added the update from Joseph
> Updated introduction

- doc/developper-documentation/architecture.md
- mkdocs.yml
REFS https://github.com/backbee/backbee-standard/issues/170
> Add architecture page

- doc/developper-documentation/cookbooks/create_new_commands.md
- mkdocs.yml
REFS https://github.com/backbee/backbee-standard/issues/170
> Added new cookbook on command creation

- README.md
- doc/developper-documentation/configuration.md
- doc/developper-documentation/installation.md
- mkdocs.yml
See https://github.com/backbee/backbee-standard/issues/170
> [WIP] - Added Installation and configuration sections

- doc/index.md
> Updated introduction (Joseph suggestions)

- doc/developper-documentation/components/config.md
- mkdocs.yml
This is docs for the BackBee Config Component
REFS https://github.com/backbee/backbee-standard/issues/223 and  https://github.com/backbee/backbee-standard/issues/170
> Added docs for Config component

- doc/developper-documentation/components/config.md
- doc/developper-documentation/components/event_listener.md
- doc/developper-documentation/components/security.md
- doc/developper-documentation/configuration.md
- mkdocs.yml
This is an updated review of https://github.com/backbee/docs/pull/10
> Review of Security and EventListener Component docs

- doc/developper-documentation/components/classcontent.md
- mkdocs.yml
This is the pull request of @froockmann updated.
Also, sorry @hbaptiste : in you case I patch your update from master because I change a lot of things (files, indentation, content, urls) and I wanted to avoid rebasing issues.
> Add parameters

- README.md
- doc/developper-documentation/cookbooks/use_swift_mailer_in_backbee.md
- mkdocs.yml
> [cookbook] Use Swift Mailer in BackBee

- README.md
- doc/developper-documentation/cookbooks/create_bundle_administration.md
- mkdocs.yml
> [cookbook] create bundle administration

- doc/developper-documentation/architecture.md
- doc/developper-documentation/components/classcontent.md
- doc/developper-documentation/components/config.md
- doc/developper-documentation/components/event_listener.md
- doc/developper-documentation/components/routing.md
- doc/developper-documentation/components/security.md
- doc/developper-documentation/configuration.md
- doc/developper-documentation/cookbooks/customize_error_pages.md
- doc/developper-documentation/cookbooks/use_swift_mailer_in_backbee.md
- doc/developper-documentation/installation.md
- doc/developper-documentation/requirements.md
- doc/index.md
This is an english review from @clementbonfils , big thanks to him !
> Cbonfils review

- README.md
- doc/developper-documentation/components/translation.md
- mkdocs.yml
> [component] Translation

- doc/developper-documentation/cookbooks/ease_debugging_with_profiler.md
- mkdocs.yml
Added new cookbook to explain what is the web profiler and how to use it.
> Added Web Profiler cookbook

- doc/developper-documentation/cookbooks/create_new_templating_helpers.md
- mkdocs.yml
A simple example to show how to create and use helpers
> Added cookbook on templating helper creation

- README.md
- doc/developper-documentation/project_architecture.md
- mkdocs.yml
> [RFR][developer] project architecture

- doc/developper-documentation/components/classcontent.md
> [component] ClassContent component

- doc/developper-documentation/components/bundle.md
- mkdocs.yml
This PR brings Bundle component documentation. The documentation plan:
- What is a bundle?
- Bundle folder structure and entry point
- How the bundle loader works?
- Default expectations
- Using recipes to custom some load
> [RFR] [developer] Bundle component documentation

- README.md
- doc/developper-documentation/components/nested_node.md
- mkdocs.yml
> [WIP][component] Nested node component

- doc/developper-documentation/installation.md
Docs are updated with the new option to install a complete demonstration website.
> updated docs on installer

- doc/developper-documentation/components/bundle.md
- doc/developper-documentation/components/cache.md
- doc/developper-documentation/components/classcontent.md
- doc/developper-documentation/components/config.md
- doc/developper-documentation/components/event_listener.md
- doc/developper-documentation/components/nested_node.md
- doc/developper-documentation/components/renderer.md
- doc/developper-documentation/components/routing.md
- doc/developper-documentation/components/security.md
- doc/developper-documentation/components/translation.md
- mkdocs.yml
This is not totaly complete.
=> backbee cache adapters
=> backbee cache validator
=> backbee cache id generator
> Added cache component

- README.md
- doc/developper-documentation/cookbooks/layout_creation.md
- mkdocs.yml
> [cookbook] Layout creation using LayoutBuilderBundle

- doc/developper-documentation/components/bundle.md
Some keys were missing from official docs 
ping @backbee/core-team
> Improved Bundle docs

- doc/developper-documentation/architecture.md
- doc/developper-documentation/configuration.md
- doc/developper-documentation/installation.md
- doc/developper-documentation/project_architecture.md
- doc/developper-documentation/requirements.md
- doc/index.md
- mkdocs.yml
> Fix typos.

- blogbee/base.html
- blogbee/contribute.html
> added note for contribution

- doc/developer-documentation/components/bundle.md
Review of english made by Elena :)
> Reviewed bundle component docs

- doc/developer-documentation/components/classcontent.md
> [Component][ClassContent][Parameters] add doc for max_entry in list elements

- doc/developer-documentation/components/classcontent.md
To be merged when backbee/backbee-standard#327 is closed
> [ClassContent] Add properties reference

- doc/developer-documentation/cookbooks/use_doctrine_commands_console.md
- mkdocs.yml
> Added Implement doctrine commands console to developer doc

- doc/developer-documentation/installation.md
Referenced issues: 
- [backbee/backbee-standard #677](https://github.com/backbee/backbee-standard/issues/677)
- [backbee/backbee-standard #619](https://github.com/backbee/backbee-standard/issues/619)
> improved 'Developer Documentation - Installation' page

- doc/developer-documentation/installation.md
Updated `installation.md` according to feedbacks from [backbee/backbee-standard#677](https://github.com/backbee/backbee-standard/issues/677)
> updated installation.md

- doc/developer-documentation/configuration.md
Referenced issue: [backbee-standard #621](https://github.com/backbee/backbee-standard/issues/621)
> updated 'Get started - Configuration' page

- doc/developer-documentation/references/events.md
- mkdocs.yml
Referenced issue: [backbee/backbee-standard #649](https://github.com/backbee/backbee-standard/issues/649)
ping @mickaelsteinberg.
> added 'Reference - Events' documentation

- doc/developer-documentation/references/dependency-injection-container.md
- mkdocs.yml
Referenced issue: [backbee/backbee-standard #645](https://github.com/backbee/backbee-standard/issues/645)
ping @mickaelsteinberg, @crouillon.
> added 'Reference - Dependency Injection Container' documentation

- doc/developer-documentation/installation.md
Visually identify 2 separate ways to install backbee
> Separate install zip and command line install
